"""empty message

Revision ID: 3598bd934bd6
Revises: 
Create Date: 2021-12-09 19:25:17.642724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3598bd934bd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('top_items', sa.String(length=100), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['favorites'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('reviews', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['reviews'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business', sa.String(length=200), nullable=True),
    sa.Column('customer', sa.String(length=50), nullable=True),
    sa.Column('review', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['business'], ['business.id'], ),
    sa.ForeignKeyConstraint(['customer'], ['customer.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('businessID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businessID'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businessto_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('businessID', sa.Integer(), nullable=True),
    sa.Column('categoryID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businessID'], ['business.id'], ),
    sa.ForeignKeyConstraint(['categoryID'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customerto_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=True),
    sa.Column('reviewID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerID'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['reviewID'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewto_business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('businessID', sa.Integer(), nullable=True),
    sa.Column('reviewID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businessID'], ['business.id'], ),
    sa.ForeignKeyConstraint(['reviewID'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businessto_business_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ownerID', sa.Integer(), nullable=True),
    sa.Column('businessID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businessID'], ['business.id'], ),
    sa.ForeignKeyConstraint(['ownerID'], ['business_owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businessto_business_owner')
    op.drop_table('reviewto_business')
    op.drop_table('customerto_review')
    op.drop_table('businessto_category')
    op.drop_table('business_owner')
    op.drop_table('review')
    op.drop_table('customer')
    op.drop_table('category')
    op.drop_table('business')
    # ### end Alembic commands ###
