"""empty message

Revision ID: 5848fe5e83c2
Revises: 
Create Date: 2021-12-01 10:27:17.353184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5848fe5e83c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('reviews', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('top_items', sa.String(length=100), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('businessID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businessID'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('businessID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businessID'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businessto_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('businessID', sa.Integer(), nullable=True),
    sa.Column('categoryID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['businessID'], ['business.id'], ),
    sa.ForeignKeyConstraint(['categoryID'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businessto_category')
    op.drop_table('category')
    op.drop_table('business_owner')
    op.drop_table('business')
    op.drop_table('customer')
    # ### end Alembic commands ###
